#!/usr/bin/env python3

import hydra
import rospy

from monitor import Viewer


if __name__ == "__main__":
    rospy.init_node('visualisation', anonymous=True)

    rospy.loginfo(f'Creating visualizer for the physical world.')

    robot_name = rospy.get_param('~robot_name') 
    config = rospy.get_param('~config')
    layout = rospy.get_param('~layout')

    hydra.initialize(config_path="../config", version_base=None)
    hydra_config = hydra.compose(config)

    viewer = Viewer.build(hydra_config, layout, robot_name)

    while not rospy.is_shutdown():
        viewer.run()

    viewer.destroy()