name: "Empty"
description: "Navigation Among Movable Obstacles: Simulated Approach"

range_x: [-4.0, 4.0]
range_y: [-4.0, 4.0]

goal: [1.0, 0.0]


environment:
    robot:
        init_state: [-3., 0., 0.]